'use strict';
const DATA=window.TRIAD_DATA;
const state={lang:'ko',study:'D',scenario:'both_shift',protocol:'triangulated',policy:'max_gap',setting:'48/1',controller:'hom_gaussian',estimator:'hom_gaussian'};
const NAMES={
 normal:['정상','Normal'],gain_shift:['표본 gain 변화','Sample gain shift'],offset_shift:['표본 offset 변화','Sample offset shift'],both_shift:['표본 gain·offset 변화','Sample gain + offset'],nonlinear_sensor:['비선형 센서','Nonlinear sensor'],blank_mismatch:['공백 기준 불일치','Mismatched blank'],spike_recovery:['첨가 회수율 오류','Spike recovery failure'],reference_drift:['독립 기준 드리프트','Reference drift'],common_anchor_failure:['기준의 공통 편향','Common anchor failure'],
 external_only:['외부 교정만','External calibration only'],addition_only:['표준 첨가','Addition only'],addition_blank:['첨가 + 공백 기준','Addition + blank'],orthogonal_only:['독립 기준 측정','Orthogonal reference'],triangulated:['세 기준 교차 점검','Triangulated anchors'],
 narrow:['좁은 국소 오류','Narrow local fault'],weak:['약한 국소 오류','Weak local fault'],broad:['넓은 오류','Broad fault'],boundary:['경계 부근 오류','Boundary fault'],t3_null:['t3 잡음 / 평균 오류 없음','t3 noise / no mean fault'],hetero_null:['이분산 / 평균 오류 없음','Heteroscedastic / no mean fault'],common_mode:['대조군도 같은 오류','Common-mode fault'],
 fixed_three:['고정 3지점 반복','Repeat three fixed sites'],uniform:['균일 무작위','Uniform random'],stratified:['층화 무작위','Stratified random'],max_gap:['가장 큰 공백','Largest-gap coverage'],adaptive_cover:['적응 + 광역 탐색','Adaptive + coverage'],
 gaussian:['정규·등분산','Homoscedastic Gaussian'],loglinear_noise:['로그선형 이분산','Loglinear variance'],nonmonotone_noise:['비단조 이분산','Nonmonotone variance'],student3:['동일 분산 t3','Variance-matched t3'],contamination:['드문 큰 잡음','Contamination'],missing_mean:['평균식 누락','Missing mean term'],
 hom_gaussian:['등분산 Gaussian','Homoscedastic Gaussian'],logvar_gaussian:['로그분산 Gaussian','Logvariance Gaussian'],student_t:['Student-t (ν=4)','Student-t (ν=4)'],random:['무작위','Random'],spacefill:['영역 채우기','Space-filling'],ivr:['적분 분산 감소','Integrated variance reduction'],
 audit_sample:['진단 표본','Audit sample'],matched_control:['짝지은 대조','Matched control'],sample:['표본','Sample'],external:['외부 교정','External calibrator'],spike:['표준 첨가','Standard addition'],blank:['공백','Blank'],reference:['독립 기준','Reference'],control:['대조','Control'],fit:['적합','Fit'],audit:['진단','Audit'],test:['최종 테스트','Final test']};
const t=(ko,en)=>state.lang==='ko'?ko:en;
const name=k=>NAMES[k]?NAMES[k][state.lang==='ko'?0:1]:k;
const num=(v,d=4)=>v==null?'—':Number(v).toFixed(d);
const pct=v=>v==null?'—':(100*v).toFixed(1)+'%';
const $=s=>document.querySelector(s);
function element(tag,text){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;return el;}
function choose(key,label,values){const l=element('label',label),s=element('select');s.id='select-'+key;s.setAttribute('aria-label',label);for(const v of values){const op=element('option',key==='setting'?t(`예산 ${v.split('/')[0]} / 대조비 ${v.split('/')[1]}`,`Budget ${v.split('/')[0]} / control ${v.split('/')[1]}`):name(v));op.value=v;s.append(op);}if(!values.includes(state[key]))state[key]=values[0];s.value=state[key];s.addEventListener('change',()=>{state[key]=s.value;render()});l.append(s);$('#filters').append(l);}
function trace(){return DATA.traces.find(r=>r.study===state.study&&r.scenario===state.scenario&&(r.study==='D'?r.protocol===state.protocol:r.study==='E'?r.policy===state.policy&&`${r.budget}/${r.control_cost}`===state.setting:r.policy===state.policy&&r.controller===state.controller));}
function render(){
 document.documentElement.lang=state.lang;document.querySelectorAll('[data-ko]').forEach(e=>e.textContent=e.dataset[state.lang]);$('#language').textContent=t('English','한국어');
 document.querySelectorAll('[data-study]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.study===state.study)));
 $('#study-title').textContent=state.study==='D'?t('교정 정보를 표본으로 옮길 수 있는가?','Does calibration transfer to the sample?'):state.study==='E'?t('같은 비용으로 어디를 점검할 것인가?','Where should we audit under the same budget?'):t('좋은 결과가 추정기 때문인가, 수집 때문인가?','Is the gain from the estimator or the acquisition policy?');
 $('#scope').textContent=state.study==='D'?t('구조적 rank는 주어진 관측 가정 아래에서 계산됩니다. 기준들이 함께 틀리면 rank가 충분해도 원인은 구분되지 않습니다.','Structural rank is conditional on measurement assumptions. Shared anchor bias can remain invisible even with full rank.'):state.study==='E'?t('새 표본–대조 측정의 차이를 점검합니다. 정규·등분산·유효 대조군 조건이 깨지면 검정 보장도 적용되지 않습니다.','Fresh sample–control contrasts are audited. Testing guarantees do not apply when Gaussian, variance, or control-validity assumptions fail.'):t('각 수집 데이터셋에 세 추정기를 모두 재적합했습니다. 수집용 추정기와 최종 추정기를 별도로 선택할 수 있습니다.','Every acquired dataset is refitted with all three estimators. The acquisition controller and final estimator are selected separately.');
 $('#filters').replaceChildren();const rows=DATA.summary[state.study];choose('scenario',t('합성 세계','Synthetic world'),[...new Set(rows.map(r=>r.scenario))]);
 if(state.study==='D')choose('protocol',t('측정 설계','Measurement design'),[...new Set(rows.map(r=>r.protocol))]);
 if(state.study==='E'){choose('policy',t('진단 위치 정책','Audit policy'),[...new Set(rows.map(r=>r.policy))]);choose('setting',t('예산 / 대조 측정비','Budget / control cost'),['24/1','48/1','48/3']);}
 if(state.study==='F'){choose('controller',t('수집용 추정기','Acquisition controller'),['hom_gaussian','logvar_gaussian','student_t']);choose('policy',t('수집 정책','Acquisition policy'),['random','spacefill','ivr']);choose('estimator',t('최종 추정기','Final estimator'),['hom_gaussian','logvar_gaussian','student_t']);}
 const r=trace();if(!r){$('#plot').textContent='Record unavailable';return;}
 $('#single-meta').textContent=t(`시드 ${r.seed} · 적합 ${r.costs.fit} / 진단 ${r.costs.audit} / 테스트 ${r.costs.test}`,`Seed ${r.seed} · fit ${r.costs.fit} / audit ${r.costs.audit} / test ${r.costs.test}`);
 $('#trace-download').href='../results/v130/traces/'+encodeURIComponent(r.filename);$('#results-doc').href=`../../docs/${state.lang}/22_TRIAD_RESULTS.md`;
 draw(r);aggregate(rows);observations(r);
}
function aggregate(rows){let list=rows.filter(r=>r.scenario===state.scenario);let headers,values,selected;
 if(state.study==='D'){headers=[t('측정 설계','Design'),'Rank',t('잠재 RMSE','Latent RMSE'),t('포함률','Coverage'),t('모형 충돌','Contradiction'),t('전달 귀무 기각','Transfer-null rejection')];values=list.map(r=>[name(r.protocol),`${r.rank}/6`,num(r.metrics.latent_rmse.mean),pct(r.metrics.latent_inclusion.mean),`${r.contradicted.k}/${r.n}`,r.transfer_rejected.n?`${r.transfer_rejected.k}/${r.n}`:'—']);selected=list.map(r=>r.protocol===state.protocol);}
 if(state.study==='E'){list=list.filter(r=>`${r.budget}/${r.control_cost}`===state.setting);headers=[t('위치 정책','Placement'),'N pairs',t('단순 경고','Naive alarm'),'Bonferroni',t('α 지출','α-spending'),t('오류 영역 진입','Region hit')];values=list.map(r=>[name(r.policy),r.n_pairs,pct(r.detection.naive.alarm.rate),pct(r.detection.bonferroni.alarm.rate),pct(r.detection.spending.alarm.rate),pct(r.hit_region.rate)]);selected=list.map(r=>r.policy===state.policy);}
 if(state.study==='F'){list=list.filter(r=>r.controller===state.controller);headers=[t('정책 / 최종 추정기','Policy / final estimator'),'RMSE','NLL','CRPS',t('관측 포함률','Observed coverage'),t('구간 폭','Interval width')];values=list.map(r=>[`${name(r.policy)} / ${name(r.estimator)}`,num(r.metrics.latent_rmse.mean),num(r.metrics.predictive_nll.mean),num(r.metrics.crps.mean),pct(r.metrics.observed_inclusion.mean),num(r.metrics.observed_width.mean)]);selected=list.map(r=>r.policy===state.policy&&r.estimator===state.estimator);}
 $('#aggregate-note').textContent=t(`각 행 ${list[0]?.n||0}개 세계 · 평균 / 비율`,`Each row: ${list[0]?.n||0} worlds · mean / rate`);table($('#summary-table'),headers,values,selected);
}
function table(el,headers,rows,selected=[]){el.replaceChildren();const h=element('thead'),hr=element('tr');headers.forEach(x=>hr.append(element('th',x)));h.append(hr);const b=element('tbody');rows.forEach((row,i)=>{const tr=element('tr');if(selected[i])tr.className='selected';row.forEach(v=>tr.append(element('td',String(v))));b.append(tr)});el.append(h,b);}
function observations(r){$('#record-note').textContent=t(`${r.observations.length}건의 직렬화 관측. 합성 측정 단위이며 생물학적 표본이 아닙니다.`,`${r.observations.length} serialized measurements. Synthetic units, not biological samples.`);table($('#observations-table'),[t('역할 / 종류','Role / kind'),'x',t('값','Value'),'Δ',t('비용','Cost')],r.observations.map(o=>[name(o.split)+' / '+name(o.kind),num(o.x,3),num(o.value),num(o.delta,2),num(o.cost,1)]));}
const SVG='http://www.w3.org/2000/svg';
function node(tag,attrs={},text){const e=document.createElementNS(SVG,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,String(v));if(text!==undefined)e.textContent=text;return e;}
function draw(r){const mobile=window.innerWidth<680;const W=mobile?390:1000,H=mobile?330:360,L=mobile?56:64,R=mobile?18:26,T=20,B=43;const x=r.curves.x;let truth,mean=null,half=null,points=[],extra=null;
 if(r.study==='D'){truth=r.curves.latent_truth;mean=r.curves.latent_mean;half=r.curves.latent_sd?.map(v=>1.96*v);}
 else if(r.study==='E'){truth=r.curves.contrast_truth;extra=r.curves.physical_fault;points=r.history.map(o=>[o.x,o.contrast]);}
 else{truth=r.curves.truth;mean=r.curves.predictions[state.estimator].mean;half=r.curves.predictions[state.estimator].halfwidth;points=x.map((v,i)=>[v,r.curves.test_y[i]]);}
 const vals=[...truth,...(extra||[]),...points.map(p=>p[1])];if(mean)mean.forEach((v,i)=>vals.push(v+(half?.[i]||0),v-(half?.[i]||0)));let lo=Math.min(...vals),hi=Math.max(...vals);const pad=(hi-lo||1)*.12;lo-=pad;hi+=pad;const sx=v=>L+(v+1)/2*(W-L-R),sy=v=>H-B-(v-lo)/(hi-lo)*(H-T-B);const svg=node('svg',{viewBox:`0 0 ${W} ${H}`,role:'img','aria-label':t('개별 합성 실행의 예측 또는 진단 그래프','Prediction or audit graph for a single synthetic run')});
 for(let i=0;i<=4;i++){const v=lo+(hi-lo)*i/4;svg.append(node('line',{x1:L,x2:W-R,y1:sy(v),y2:sy(v),stroke:'#dce4e8'}));svg.append(node('text',{x:L-9,y:sy(v)+5,'text-anchor':'end','font-size':mobile?16:14,fill:'#4e6470'},v.toFixed(2)));}
 [-1,-.5,0,.5,1].forEach(v=>svg.append(node('text',{x:sx(v),y:H-16,'text-anchor':'middle','font-size':mobile?16:14,fill:'#4e6470'},v.toFixed(1))));
 const path=(ys)=>ys.map((v,i)=>(i?'L':'M')+sx(x[i])+','+sy(v)).join(' ');
 if(mean&&half){const pts=x.map((v,i)=>[sx(v),sy(mean[i]+half[i])]).concat(x.map((v,i)=>[sx(v),sy(mean[i]-half[i])]).reverse());svg.append(node('polygon',{points:pts.map(p=>p.join(',')).join(' '),fill:'#d7e9ed'}));}
 if(extra&&extra.some((v,i)=>Math.abs(v-truth[i])>1e-9))svg.append(node('path',{d:path(extra),fill:'none',stroke:'#b37323','stroke-width':2,'stroke-dasharray':'7 5'}));
 svg.append(node('path',{d:path(truth),fill:'none',stroke:'#192b35','stroke-width':2.5}));if(mean)svg.append(node('path',{d:path(mean),fill:'none',stroke:'#087e93','stroke-width':2.5}));
 points.forEach(([xx,yy])=>svg.append(node('circle',{cx:sx(xx),cy:sy(yy),r:3,fill:'#567884',opacity:.65})));
 $('#plot').replaceChildren(svg);$('#legend').replaceChildren();function key(label,color){const e=element('span');e.className='key';const sw=element('i');sw.className='swatch';sw.style.background=color;e.append(sw,element('span',label));$('#legend').append(e)}
 key(r.study==='E'?t('대조 차이의 참값','True sample–control contrast'):t('잠재 참값 (평가 전용)','Latent truth (evaluator only)'),'#192b35');if(mean){key(t('추정 평균','Estimated mean'),'#087e93');key(r.study==='D'?t('근사 95% 잠재 구간','Approx. 95% latent interval'):t('근사 95% 관측 구간','Approx. 95% predictive interval'),'#b9d8df');}if(points.length)key(t('잡음 관측','Noisy observations'),'#567884');if(extra&&extra.some((v,i)=>Math.abs(v-truth[i])>1e-9))key(t('공통 물리 오류 (대조로 상쇄)','Common physical fault (cancels in contrast)'),'#b37323');
 $('#run-note').textContent=r.study==='D'?t(`상태: ${r.model.status} · rank ${r.model.expanded_physical_rank}/6. ${mean?'추정치는 기준 가정에 조건부입니다. 모형 충돌 경고는 자동 보정이 아닙니다.':'관측만으로 유일한 잠재 반응을 추정할 수 없어 예측 구간을 표시하지 않습니다.'}`,`Status: ${r.model.status} · rank ${r.model.expanded_physical_rank}/6. ${mean?'Estimates are conditional on anchor assumptions. Contradiction does not automatically repair the model.':'No unique latent estimate; no prediction interval is displayed.'}`):r.study==='E'?t(`새 관측 쌍 ${r.n_pairs}개. 그래프의 참값·오류 위치는 수집 정책에 전달되지 않습니다.`,`There are ${r.n_pairs} fresh measurement pairs. Ground truth and fault locations are not supplied to the policy.`):t(`최종 추정기: ${name(state.estimator)}. 관측 구간이 넓어져도 잠재 평균의 오류가 해결됐다는 뜻은 아닙니다.`,`Final estimator: ${name(state.estimator)}. Wider predictive intervals do not imply a repaired mean function.`);
}
$('#language').addEventListener('click',()=>{state.lang=state.lang==='ko'?'en':'ko';render()});document.querySelectorAll('[data-study]').forEach(b=>b.addEventListener('click',()=>{state.study=b.dataset.study;state.scenario=b.dataset.study==='D'?'both_shift':b.dataset.study==='E'?'narrow':'contamination';state.policy=b.dataset.study==='F'?'random':'max_gap';render()}));render();

let resizeFrame;window.addEventListener('resize',()=>{cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(()=>{const r=trace();if(r)draw(r)});});
