(()=>{'use strict';
const D=window.BOUNDED_DATA,$=id=>document.getElementById(id);let lang='ko',study='G';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const t=(k,e)=>lang==='ko'?k:e;
const names={G:['편향과 허용 집합','Bias and feasible sets'],H:['분산을 모르는 진단','Unknown-scale controls'],I:['반복과 오차 분해','Replicate decomposition']};
const scenarios={normal:['정상','Normal'],bounded_bias:['허용 범위 내 기준 편향','Bounded reference bias'],common_in_bounds:['범위 안의 공통 편향','Common bias in bounds'],common_out_of_bounds:['범위 밖의 공통 편향','Common bias outside bounds'],nonlinear_sensor:['비선형 센서','Nonlinear sensor'],correlated_repeats:['반복 간 공유오차','Correlated repeats'],gaussian_null:['Gaussian 정상 대비','Gaussian contrast null'],hetero_null:['이분산 정상 대비','Heteroscedastic null'],symmetric_t3_null:['대칭 t3 정상 대비','Symmetric t3 null'],skew_mean_null:['평균 0 · 비대칭','Zero mean, asymmetric'],broad_mean:['광역 평균 변화','Broad mean change'],narrow_mean:['좁은 국소 변화','Narrow local change'],weak_narrow:['약한 국소 변화','Weak local change'],common_mode:['대조와 표본의 공통 변화','Common-mode change'],heteroscedastic:['이분산','Heteroscedastic'],mean_missing:['평균 항 누락','Missing mean term'],combined:['평균 항 누락 + 이분산','Missing mean + heteroscedastic'],local_missing:['기저에 없는 국소 변화','Unrepresented local bump'],contamination:['큰 오염 잡음','Contaminated noise'],shared_batch:['공유 배치오차','Shared batch effect'],within_batch_drift:['반복 단계 드리프트','Within-batch phase drift']};
const methods={reference_only:['기준 측정만','Reference only'],addition_blank:['첨가 + 공백','Addition + blank'],triangulated:['세 기준 결합','Triangulated'],assume_unbiased:['편향 0 가정','Assume no bias'],bounded:['선언한 편향 범위','Declared bounds'],wide:['편향 범위 2배','Double-width bounds'],nominal_z:['고정 분산 z','Nominal-scale z'],local_t_bonferroni:['위치별 t + 보정','Local t + Bonferroni'],conditional_sign_e:['조건부 부호 e','Conditional-sign e'],pooled_base:['동일 분산 · 기본 평균','Pooled variance / base mean'],residual_logvar_base:['잔차 분산 · 기본 평균','Residual variance / base mean'],difference_logvar_base:['반복 차이 분산 · 기본 평균','Difference variance / base mean'],difference_logvar_plus:['반복 차이 + 추가 평균 항','Difference variance + mean term'],plus_bootstrap:['추가 평균 항 + bootstrap','Mean term + bootstrap'],max_gap:['최대 공백','Maximum gap'],adaptive_cover:['적응 탐색 + 광역 커버','Adaptive + coverage']};
function name(x,map=methods){return map[x]?.[lang==='ko'?0:1]||x}
function num(x){return x==null?'—':Number(x).toFixed(4)}
function metric(r,k){return r.metrics[k]?.mean??null}
function bool(r,k){let m=r.metrics[k];return !m?.n?t('진단 안 함','Not monitored'):`${m.count}/${m.n} · ${(m.mean*100).toFixed(1)}%`}
function options(el,items,current,label){el.innerHTML=items.map(v=>`<option value="${esc(v)}">${esc(label(v))}</option>`).join('');el.value=items.includes(current)?current:items[0]}
function text(){document.documentElement.lang=lang;$('language').textContent=t('English','한국어');$('tag').textContent='BOUNDED EVIDENCE / SYNTHETIC RESEARCH';$('title').textContent=t('가정을 숨기지 않는 연구','Research that keeps assumptions visible');$('intro').textContent=t('기준 편향, 미지 분산, 반복 측정. 서로 다른 불확실성을 한 숫자로 합치지 않고, 세 가지 작은 실험으로 검사합니다.','Reference bias, unknown variance and replication. Three small experiments separate uncertainties instead of collapsing them into one number.');$('status').textContent=t('8,208개 합성 실행 · 실제 생물 표본 0개','8,208 synthetic runs · 0 biological samples');$('scope').textContent=t('저장된 평가 결과 · 새 계산은 Python CLI','Saved evaluation results · new computation uses the Python CLI');$('scenario-label').textContent=t('합성 세계','Synthetic world');$('design-label').textContent=study==='I'?t('입력당 기술적 반복','Technical repeats per input'):t('측정 설계 / 위치 정책','Measurement / location design');$('fraction-label').textContent=t('진단 예산 비중','Audit budget share');$('fraction-wrapper').hidden=study!=='H';$('assumption-title').textContent=t('판단에 필요한 조건','Conditions for interpretation');$('aggregate-title').textContent=t('여러 세계의 집계','Across-world summary');$('single-title').textContent=t('대표 실행 1개','One representative run');$('raw').textContent=t('원본 JSON 열기','Open raw JSON');$('report').textContent=t('평가 보고서','Results report');$('history').textContent=t('버전별 연구 자료','Release history');$('report').href=`../../docs/${lang}/29_BOUNDED_RESULTS.md`;$('history').href=lang==='ko'?'../../../VERSIONS.md':'../../../VERSIONS.en.md';$('footer-note').textContent=t('통계 조건 충족과 실제 기전 검증은 다릅니다.','Statistical validity is not biological mechanism validation.');document.querySelectorAll('[data-study]').forEach(b=>{b.classList.toggle('active',b.dataset.study===study);b.querySelector('span').textContent=names[b.dataset.study][lang==='ko'?0:1];b.setAttribute('aria-pressed',b.dataset.study===study?'true':'false')})}
function setup(reset=false){let sc=$('scenario').value,dc=$('design').value; text();let rows=D.summary.filter(r=>r.study===study);let scenes=[...new Set(rows.map(r=>r.scenario))];options($('scenario'),scenes,reset?({G:'common_in_bounds',H:'hetero_null',I:'mean_missing'}[study]):sc,v=>name(v,scenarios));let designs=[...new Set(rows.map(r=>String(study==='G'?r.design:study==='H'?r.policy:r.repeats)))];options($('design'),designs,reset?({G:'triangulated',H:'max_gap',I:'4'}[study]):dc,v=>study==='I'?v+t('회',' repeats'):name(v));if(reset)$('fraction').value='.5';if($('fraction').value==='')$('fraction').value='0.5';render()}
function rows(){return D.summary.filter(r=>r.study===study&&r.scenario===$('scenario').value&&(study==='G'?r.design===$('design').value:study==='H'?r.policy===$('design').value&&r.audit_fraction===Number($('fraction').value):r.repeats===Number($('design').value)))}
function representative(){return D.traces.find(r=>r.study===study&&r.scenario===$('scenario').value&&(study==='G'?r.design===$('design').value:study==='H'?r.policy===$('design').value&&r.audit_fraction===Number($('fraction').value):r.repeats===Number($('design').value)))}
function render(){if(study==='H'){const z=$('fraction').querySelector('option[value="0"]');z.disabled=$('design').value==='adaptive_cover';if(z.disabled&&Number($('fraction').value)===0)$('fraction').value='0.25'}let rr=rows();if(!rr.length){$('results').innerHTML='';$('figure').textContent=t('이 조합은 실행하지 않았습니다. 진단 0%는 최대 공백 정책의 공통 비진단 기준선입니다.','This combination was not run. Zero auditing is represented by the shared max-gap no-audit baseline.');$('aggregate-n').textContent='0';$('raw').removeAttribute('href');return}
$('aggregate-n').textContent=`n = ${rr[0].runs} ${t('세계 / 분석별','worlds per analysis')}`;
let heads=study==='G'?[t('허용 가정','Assumptions'),t('θ₀ 포함','θ₀ inclusion'),t('전체 q 포함','Joint q inclusion'),t('공집합','Empty sets'),t('θ₀ 폭 · 유효 n','θ₀ width / available n')]:study==='H'?[t('경고 규칙','Monitor'),t('경고 횟수','Alarm'),t('실제 수집비','Actual acquisition cost'),'RMSE',t('관측 포함률','Observation inclusion')]:[t('최종 추정기','Final estimator'),'RMSE','NLL',t('잠재 포함률','Latent inclusion'),t('관측 포함률 / 폭','Observation inclusion / width')];
let body=rr.map(r=>{let cells=study==='G'?[bool(r,'theta0_in_projection'),bool(r,'joint_truth_in_set'),bool(r,'empty'),`${num(metric(r,'theta0_width'))} · n=${r.metrics.theta0_width.n}`]:study==='H'?[bool(r,'alarm'),num(metric(r,'acquisition_spend')),num(metric(r,'rmse')),num(metric(r,'observed_coverage'))]:[num(metric(r,'rmse')),num(metric(r,'nll')),num(metric(r,'latent_coverage')),`${num(metric(r,'observed_coverage'))} / ${num(metric(r,'observed_width'))}`];return `<tr><td>${esc(name(r.variant))}<small>${esc(r.variant)}</small></td>${cells.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`}).join('');$('results').innerHTML='<thead><tr>'+heads.map(h=>'<th scope="col">'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+body+'</tbody>';

if(study==='G')$('assumption-text').textContent=t('편향의 허용 범위는 외부 가정입니다. 공집합이 아니라도 참값을 제외할 수 있습니다. 그룹 내 독립 Gaussian 반복과 고정된 측정 횟수가 신뢰집합의 조건입니다.','Bias bounds are external assumptions. A feasible set can still exclude truth. The confidence construction requires within-group independent Gaussian repeats and fixed group sizes.');
if(study==='H')$('assumption-text').textContent=t('위치별 t는 같은 위치의 독립 Gaussian 반복, 부호 e는 과거와 위치에 조건부인 부호 균형이 필요합니다. 세 경고를 OR 결합하지 않았습니다. 평균 0만으로 부호 조건이 충족되지는 않습니다.','Local t requires independent Gaussian repeats at each location; sign e requires conditional sign balance given past data and location. The three monitors are not OR-combined. Zero mean alone is insufficient for sign validity.');
if(study==='I')$('assumption-text').textContent=t('기술적 차이는 같은 그룹의 공유 평균을 지웁니다. 공유 배치오차도 함께 사라지므로 총분산을 모두 추정하지 못합니다. 추가 평균 항은 사전에 정한 sin(πx)이며 자동 기전 발견이 아닙니다.','Technical differences remove the shared group mean—and shared batch errors. They do not identify total variance. The additional sin(πx) term was prespecified, not automatically discovered.');
$('metric-note').textContent=t('좁은 화면에서는 표·그래프를 가로로 스크롤할 수 있습니다. 포함률·경고율·오차는 서로 다른 지표입니다. 낮은 NLL이 유리하며 음수가 될 수 있습니다. 공집합은 실패 분모에 유지하고 폭 평균에서만 제외합니다.','Tables and plots scroll horizontally on small screens. Inclusion, alarms and error are distinct metrics. Lower NLL is better and may be negative. Empty sets remain in failure denominators and are omitted only from width means.');let r=representative();$('raw').href=r.path;$('single-note').textContent=t('아래 그림은 시드 73000의 한 실행입니다. 위 표의 평균이 아니며 평가자만 아는 참값은 사후 비교용입니다.','Below is one seed-73000 run, not the aggregate above. Evaluator-only truth is shown only for post-run comparison.');$('record').textContent='SHA-256 · '+r.record_digest;draw(r)}
function frame(content,legend=''){return `<svg viewBox="0 0 920 290" role="img" aria-label="${esc(t('합성 평가 기록 그래프','Synthetic evaluation record chart'))}">${content}</svg>`+(legend?'<div class="plot-legend">'+legend+'</div>':'')}
function draw(r){if(study==='G'){let fs=Object.entries(r.fits),truth=r.truth.theta0,vals=[truth];fs.forEach(([k,f])=>{let p=f.projections.theta0;if(p)vals.push(p.low,p.high)});let lo=Math.min(...vals)-.06,hi=Math.max(...vals)+.06;let X=v=>240+(v-lo)/(hi-lo)*620;let c='';for(let k=0;k<5;k++){let v=lo+(hi-lo)*k/4,x=X(v);c+=`<line x1="${x}" x2="${x}" y1="22" y2="230" stroke="#34434b"/><text x="${x}" y="257" text-anchor="middle">${v.toFixed(2)}</text>`}c+=`<line x1="${X(truth)}" x2="${X(truth)}" y1="22" y2="230" stroke="#e3b979" stroke-width="2" stroke-dasharray="5 4"/>`;fs.forEach(([k,f],i)=>{let y=65+i*70,p=f.projections.theta0;c+=`<text x="10" y="${y+4}">${esc(name(k))}</text>`;if(p)c+=`<line x1="${X(p.low)}" x2="${X(p.high)}" y1="${y}" y2="${y}" stroke="#85d7c9" stroke-width="8"/><text x="${X(p.high)+8}" y="${y+4}">${(p.high-p.low).toFixed(3)}</text>`;else c+=`<text x="250" y="${y+4}">${esc(t('공집합','Empty set'))}</text>`});$('figure').innerHTML=frame(c,t('선: θ₀ 허용 구간 · 점선: 합성 참값','Line: allowed θ₀ range · dashed: synthetic truth'))}
else if(study==='H'){if(!r.history.length){$('figure').innerHTML='<p class="empty-plot">'+t('이 실행은 진단 관측을 수집하지 않았습니다. 경고율 0이 아니라 진단 안 함입니다.','No audit observations in this run. This is unmonitored, not an alarm rate of zero.')+'</p>';return}let max=Math.max(...r.history.map(h=>h.cumulative_audit_cost)),ys=[0,...r.history.map(h=>h.mean_difference)],yl=Math.min(...ys)-0.12,yh=Math.max(...ys)+0.12,Y=v=>235-(v-yl)/(yh-yl)*205;let c=`<line x1="65" x2="865" y1="${Y(0)}" y2="${Y(0)}" stroke="#9babb5" stroke-dasharray="4 4"/>`; r.history.forEach((h,i)=>{let x=65+h.cumulative_audit_cost/(max||1)*760,y=Y(h.mean_difference);c+=`<circle cx="${x}" cy="${y}" r="5" fill="#85d7c9"/><text x="${x}" y="270" text-anchor="middle">${h.cumulative_audit_cost.toFixed(1)}</text><text x="${x}" y="${y-15}" text-anchor="middle">x=${h.x.toFixed(2)}</text>`;if(i){let a=r.history[i-1];c+=`<line x1="${65+a.cumulative_audit_cost/max*760}" y1="${Y(a.mean_difference)}" x2="${x}" y2="${y}" stroke="#85d7c9"/>`}});c+='<text x="10" y="28">Δ mean</text>';$('figure').innerHTML=frame(c,t('가로: 누적 진단비 · 세로: 표본–대조 평균 차이 · 표기: 선택 위치','Horizontal: audit cost · vertical: sample–control mean difference · labels: queried location'))}
else{let grid=r.grid, curves=[['synthetic truth',r.latent_response,'#e3b979'],['base',r.curves.difference_logvar_base.mean,'#9cb3d9'],['plus',r.curves.difference_logvar_plus.mean,'#85d7c9']];let values=curves.flatMap(v=>v[1]);let lo=Math.min(...values)-.08,hi=Math.max(...values)+.08;let X=v=>65+(v+1)*400,Y=v=>240-(v-lo)/(hi-lo)*210;let c='';for(let i=0;i<5;i++){let y=lo+(hi-lo)*i/4;c+=`<line x1="65" x2="865" y1="${Y(y)}" y2="${Y(y)}" stroke="#34434b"/><text x="10" y="${Y(y)+5}">${y.toFixed(2)}</text>`}for(let x of [-1,0,1])c+=`<text x="${X(x)}" y="270" text-anchor="middle">${x}</text>`;curves.forEach(([n,ys,col])=>{let d=ys.map((v,i)=>(i?'L':'M')+X(grid[i])+','+Y(v)).join(' ');c+=`<path d="${d}" fill="none" stroke="${col}" stroke-width="2.5"/>`});$('figure').innerHTML=frame(c,t('황색: 합성 참 평균 · 청색: 반복 차이+기본식 · 녹색: 추가 평균 항','Gold: synthetic mean · blue: differences/base mean · teal: added mean term'))}}
$('language').onclick=()=>{lang=lang==='ko'?'en':'ko';setup()};document.querySelectorAll('[data-study]').forEach(b=>b.onclick=()=>{study=b.dataset.study;setup(true)});['scenario','design','fraction'].forEach(id=>$(id).onchange=render);setup(true);
})();